[package]
name = "bevy_ldtk_levels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13"
serde = "1.0"
serde_json = "1.0"
hex = "0.4"
futures-either = "0.1"
path-clean = "1.0"
image = "0.24"

[features]
default = ["enable_reflect"]
enable_reflect = []

[[example]]
name = "top_down"
path = "examples/top_down.rs"

[dev-dependencies]
bevy-inspector-egui = "0.24"
