[package]
name = "ldtk_bevy_loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "example"
path = "examples/example.rs"

[dependencies]
# bevy = "0.11"
bevy = { git = "https://github.com/bevyengine/bevy.git", branch = "main" }
hex = "0.4"
serde = "1.0"
serde_json = "1.0"
futures = "0.3"

[dev-dependencies]
# bevy-inspector-egui = "0.20"
