use path_clean::PathClean;
use std::path::PathBuf;

use bevy::{prelude::*, utils::HashMap};

use super::{level::LevelAsset, world::WorldAsset};

/// An asset representing the entire ldtk project
#[derive(Asset, Debug, TypePath)]
pub struct ProjectAsset {
    pub(crate) asset_path: PathBuf,
    pub(crate) base_directory: PathBuf,
    pub(crate) exports_directory: PathBuf,
    pub(crate) worlds: HashMap<String, Handle<WorldAsset>>,
    pub(crate) levels: HashMap<String, Handle<LevelAsset>>,
    #[dependency]
    pub(crate) tilesets: Vec<Handle<Image>>,
    #[dependency]
    pub(crate) backgrounds: Vec<Handle<Image>>,
}

impl ProjectAsset {
    /// Returns a hashmap of the worlds in this project
    pub fn worlds(&self) -> &HashMap<String, Handle<WorldAsset>> {
        &self.worlds
    }

    /// Returns a hashmap of the levels in this project
    pub fn levels(&self) -> &HashMap<String, Handle<LevelAsset>> {
        &self.levels
    }
    /// Returns a list of handles to all tilesets in this project
    pub fn tilesets(&self) -> impl Iterator<Item = &Handle<Image>> {
        self.tilesets.iter()
    }

    /// Returns a list of handles to all background images in this project
    pub fn backgrounds(&self) -> &[Handle<Image>] {
        self.backgrounds.as_ref()
    }

    /// Returns the path to this project file
    pub fn asset_path(&self) -> &PathBuf {
        &self.asset_path
    }

    /// Expects a path as given from the ldtk json, and returns that path
    /// refactored as a path utilizable by the Bevy asset crate.
    ///
    /// For example: a given ldtk project might reside in the assets folder
    /// with a path like: "ldtk/my_awesome_world.ldtk", and this project might
    /// use a tileset in a layer with a path like: "tilesets/cool_layer_tileset.png".
    /// The ldtk file will provide a relative path such as "../tilesets/cool_layer_tileset.png"
    /// which will make no sense to Bevy, so we provide this function to rectify this.
    /// Passing the above into this function will result in the correct path according
    /// to Bevy, by first combining the directory where the project is and the provided
    /// relative path: "ldtk/../tilesets/cool_layer_tileset.png" and then sanitizing
    /// it with the .clean() function provided by the path-clean crate like so:
    /// "tilesets/cool_layer_tileset.png"
    pub fn ldtk_path_to_asset_path(&self, path: &PathBuf) -> PathBuf {
        self.base_directory.join(path).clean()
    }

    /// Similar to ldtk_path_to_asset_path, except we assume a directory
    /// with the name of the project was created for assets generated by
    /// ldtk. One example would be tile layer images generated by the
    /// export tile layers as images feature.
    pub fn ldtk_export_path_to_asset_path(&self, path: &str) -> PathBuf {
        self.exports_directory.join(path).clean()
    }
}
