use std::path::{Path, PathBuf};

use bevy::{prelude::*, utils::HashMap};

use crate::{ldtk, util::ldtk_path_to_asset_path};

use super::{level::LevelAsset, world::WorldAsset};

/// An asset representing the entire ldtk project
#[derive(Asset, Debug, TypePath)]
pub struct ProjectAsset {
    pub(crate) world_handles: HashMap<String, Handle<WorldAsset>>,
    pub(crate) level_handles: HashMap<String, Handle<LevelAsset>>,
    pub(crate) tileset_handles: HashMap<String, Handle<Image>>,
    pub(crate) background_handles: HashMap<String, Handle<Image>>,
    pub(crate) entity_definitions: HashMap<i64, ldtk::EntityDefinition>,
    pub(crate) enum_definitions: HashMap<i64, ldtk::EnumDefinition>,
    pub(crate) layer_definitions: HashMap<i64, ldtk::LayerDefinition>,
    pub(crate) tileset_definitions: HashMap<i64, ldtk::TilesetDefinition>,
    pub(crate) asset_path: PathBuf,
    pub(crate) base_directory: PathBuf,
    pub(crate) exports_directory: PathBuf,
    pub(crate) value: ldtk::LdtkJson,
}

// Getters
impl ProjectAsset {
    /// Returns a hashmap of the worlds in this project, indexed by identifier
    pub fn world_handles(&self) -> &HashMap<String, Handle<WorldAsset>> {
        &self.world_handles
    }

    /// Returns a hashmap of the levels in this project, indexed by identifier
    pub fn level_handles(&self) -> &HashMap<String, Handle<LevelAsset>> {
        &self.level_handles
    }
    /// Returns a hashmap of handles to all tilesets in this project,
    /// indexed by their ldtk paths
    pub fn tileset_handles(&self) -> &HashMap<String, Handle<Image>> {
        &self.tileset_handles
    }

    /// Returns a list of handles to all background images in this project,
    /// indexed by their ldtk paths
    pub fn background_handles(&self) -> &HashMap<String, Handle<Image>> {
        &self.background_handles
    }

    /// Returns the path to this project file
    pub fn asset_path(&self) -> &PathBuf {
        &self.asset_path
    }

    /// The entity definitions from the LDtk project.
    pub fn entity_definitions(&self) -> &HashMap<i64, ldtk::EntityDefinition> {
        &self.entity_definitions
    }

    /// The enum definitions from the LDtk project.
    pub fn enum_definitions(&self) -> &HashMap<i64, ldtk::EnumDefinition> {
        &self.enum_definitions
    }

    /// The layer definitions from the LDtk project.
    pub fn layer_definitions(&self) -> &HashMap<i64, ldtk::LayerDefinition> {
        &self.layer_definitions
    }

    /// The tileset definitions from the LDtk project.
    pub fn tileset_definitions(&self) -> &HashMap<i64, ldtk::TilesetDefinition> {
        &self.tileset_definitions
    }

    /// The raw imported and deserialized JSON data
    pub fn value(&self) -> &ldtk::LdtkJson {
        &self.value
    }
}

// Helpers for finding asset paths
impl ProjectAsset {
    /// Expects a path as given from the ldtk json, and returns that path
    /// refactored as a path utilizable by the Bevy asset crate.
    ///
    /// For example: a given ldtk project might reside in the assets folder
    /// with a path like: "ldtk/my_awesome_world.ldtk", and this project might
    /// use a tileset in a layer with a path like: "tilesets/cool_layer_tileset.png".
    /// The ldtk file will provide a relative path such as "../tilesets/cool_layer_tileset.png"
    /// which will make no sense to Bevy, so we provide this function to rectify this.
    /// Passing the above into this function will result in the correct path according
    /// to Bevy, by first combining the directory where the project is and the provided
    /// relative path: "ldtk/../tilesets/cool_layer_tileset.png" and then sanitizing
    /// it with the .clean() function provided by the path-clean crate like so:
    /// "tilesets/cool_layer_tileset.png"
    pub fn ldtk_path_to_asset_path(&self, ldtk_path: &Path) -> PathBuf {
        ldtk_path_to_asset_path(&self.base_directory, ldtk_path)
    }

    /// Similar to ldtk_path_to_asset_path, except we assume a directory
    /// with the name of the project was created for assets generated by
    /// ldtk. One example would be tile layer images generated by the
    /// export tile layers as images feature.
    pub fn ldtk_export_path_to_asset_path(&self, ldtk_path: &Path) -> PathBuf {
        ldtk_path_to_asset_path(&self.exports_directory, ldtk_path)
    }
}

impl ProjectAsset {}
