use path_clean::PathClean;
use std::path::PathBuf;

use bevy::{prelude::*, utils::HashMap};

use super::world::WorldAsset;

/// An asset representing the entire ldtk project
#[derive(Asset, Debug, TypePath)]
pub struct ProjectAsset {
    pub(crate) asset_path: PathBuf,
    pub(crate) base_directory: PathBuf,
    pub(crate) exports_directory: PathBuf,
    #[dependency]
    pub(crate) tilesets: Vec<Handle<Image>>,
    pub(crate) worlds: HashMap<String, Handle<WorldAsset>>,
}

impl ProjectAsset {
    /// Returns an iterator listing all world identifiers
    pub fn world_identifiers(&self) -> impl Iterator<Item = &String> {
        self.worlds.keys()
    }

    /// Returns an iterator of all asset handles to all worlds in this project
    pub fn world_handles(&self) -> impl Iterator<Item = &Handle<WorldAsset>> {
        self.worlds.values()
    }

    /// Returns an iterator of tuples, containing the identifier and handle
    /// of all worlds in this project
    pub fn world_names_and_handles(&self) -> impl Iterator<Item = (&String, &Handle<WorldAsset>)> {
        self.worlds.iter()
    }

    /// Returns an option containing the handle for a world with a given unique
    /// identifier, or None
    pub fn get_world_by_identifier(&self, identifier: &str) -> Option<&Handle<WorldAsset>> {
        self.worlds.get(identifier)
    }

    /// Returns an iterator over all tilesets outlined by this project
    pub fn tilesets(&self) -> impl Iterator<Item = &Handle<Image>> {
        self.tilesets.iter()
    }

    /// Returns the path to this project file
    pub fn get_asset_path(&self) -> &PathBuf {
        &self.asset_path
    }

    /// Expects a path as given from the ldtk json, and returns that path
    /// refactored as a path utilizable by the Bevy asset crate.
    ///
    /// For example: a given ldtk project might reside in the assets folder
    /// with a path like: "ldtk/my_awesome_world.ldtk", and this project might
    /// use a tileset in a layer with a path like: "tilesets/cool_layer_tileset.png".
    /// The ldtk file will provide a relative path such as "../tilesets/cool_layer_tileset.png"
    /// which will make no sense to Bevy, so we provide this function to rectify this.
    /// Passing the above into this function will result in the correct path according
    /// to Bevy, by first combining the directory where the project is and the provided
    /// relative path: "ldtk/../tilesets/cool_layer_tileset.png" and then sanitizing
    /// it with the .clean() function provided by the path-clean crate like so:
    /// "tilesets/cool_layer_tileset.png"
    pub fn ldtk_path_to_asset_path(&self, path: &PathBuf) -> PathBuf {
        self.base_directory.join(path).clean()
    }

    /// Similar to ldtk_path_to_asset_path, except we assume a directory
    /// with the name of the project was created for assets generated by
    /// ldtk. One example would be tile layer images generated by the
    /// export tile layers as images feature.
    pub fn ldtk_export_path_to_asset_path(&self, path: &str) -> PathBuf {
        self.exports_directory.join(path).clean()
    }
}
